[package]
name = "stormsql"
version = "0.1.0-beta.0"
edition = "2021"
authors = ["Selim Kentel <selimkentel@gmail.com>"]
description = "Service of litestorm for driving sql"
keywords = ["stormsql", "litestorm", "async", "rust", "sql"]
repository = "https://github.com/Kleinmarb/litestorm"
homepage = "https://github.com/Kleinmarb/litestorm"
documentation = "https://docs.rs/liteapi"
categories = ["network-programming", "asynchronous"]
license = "MIT"
readme = "README.md"

[lib]
name = "stormsql"
path = "src/lib.rs"

[dependencies]
