[package]
name = "litecache"
version = "0.1.0-beta.0"
edition = "2021"
authors = ["Selim Kentel <selimkentel@gmail.com>"]
description = "Service of litestorm for caching"
keywords = ["litestorm", "litecache", "async", "rust", "cache"]
repository = "https://github.com/Kleinmarb/litestorm"
homepage = "https://github.com/Kleinmarb/litestorm"
documentation = "https://docs.rs/liteapi"
categories = ["caching", "asynchronous"]
license = "MIT"
readme = "README.md"

[lib]
name = "litecache"
path = "src/lib.rs"

[dependencies]
